// Quotes per phase for multi-citation revelations
// Each export is a readonly array of strings

export const PHASE_1_QUOTES = [
  "Whoever exalts himself will be humbled; whoever humbles himself will be exalted. (Luke 14:11)",
  "Pride is the fog that hides the soul's horizon.",
  "The mask is born from fear — fear of not being loved.",
  "The ego is the wound that pretends to be the healer.",
  "Do not seek to appear; seek to be.",
  "When you stop trying to impress, you start to express.",
  "The mask falls when truth becomes more valuable than applause.",
  "Whoever hides his weakness also hides his light.",
  "A man who seeks validation is still a child in disguise.",
  "True strength is silent, not showy.",
  "The one who boasts about his goodness has already lost it.",
  "Hypocrisy is self-hatred wearing perfume.",
  "Authenticity is not rebellion — it is alignment.",
  "Let your yes be yes and your no be no. (Matthew 5:37)",
  "You are not what others think — you are what God whispers.",
  "Ego seeks to dominate; spirit seeks to illuminate.",
  "Your masks may fool the world, but they tire the soul.",
  "Self-awareness is the sword that cuts illusion.",
  "Whoever walks in humility walks in peace.",
  "To know yourself is to stop pretending.",
  "The mask hides pain; honesty heals it.",
  "You cannot fake light — it either shines or it doesn't.",
  "The proud fall because they stand on nothing.",
  "In losing image, you gain essence.",
  "The divine can only enter through the cracks of your humility.",
] as const

export const PHASE_2_QUOTES = [
  "Fear is faith turned upside down.",
  "Control is the prison of the insecure.",
  "The one who trusts flows; the one who fears clings.",
  "You are not in control — you are in care. (Matthew 6:26)",
  "What you fear to release reveals your idol.",
  "Let it go, and watch how life starts moving again.",
  "He who walks in trust never drowns, even in the storm.",
  "Faith and control cannot coexist.",
  "Let go of the illusion of mastery; embrace divine rhythm.",
  "God’s will is not against you; it is beyond you.",
  "You do not lose control — you lose the illusion of separation.",
  "Surrender is not weakness; it is the highest intelligence.",
  "Whoever tries to force outcomes loses alignment.",
  "The peace you seek is on the other side of letting go.",
  "Do not fear uncertainty; it is the soil of revelation.",
  "You cannot walk on water while clinging to the shore.",
  "Fear ends when you look it in the eye and still say \"Thy will be done.\"",
  "True courage is gentle trust.",
  "Do not worry — your path is already written. (Matthew 6:34)",
  "Worry does not lengthen life; it shortens peace.",
  "Faith is the art of resting in movement.",
  "Stop trying to play God — and start walking with Him.",
  "Fear loses power when faced with gratitude.",
  "Control is resistance; trust is rhythm.",
  "The soul that trusts is untouchable.",
] as const

export const PHASE_3_QUOTES = [
  "Desire is sacred energy — direct it, don’t deny it.",
  "Passion without conscience is a weapon.",
  "Every temptation hides a forgotten thirst for God.",
  "You cannot extinguish fire; you must give it purpose.",
  "The flesh screams louder when the soul is hungry.",
  "Lust is the counterfeit of love.",
  "Seek the fire that refines, not the one that consumes.",
  "The serpent whispers, ‘Take now.’ The spirit says, ‘Become first.’",
  "Do not fight desire — sublimate it.",
  "What you crave reveals what you lack in awareness.",
  "Desire without direction destroys the dream.",
  "Pleasure is temporary; purpose is eternal.",
  "Turn hunger into devotion.",
  "Do not mistake excitement for alignment.",
  "The fire of passion, when mastered, becomes the flame of creation.",
  "What burns you now can one day fuel your calling.",
  "The holiest passions are those anchored in meaning.",
  "The world sells addiction; God offers ascension.",
  "Desire is not sin — slavery to it is.",
  "Channel your energy, or it will channel you.",
  "The Spirit transforms desire into creative power.",
  "Discipline is the doorway through which fire becomes light.",
  "Beware of wanting without wisdom.",
  "True desire is born from love, not lack.",
  "The saint and the sinner share the same fire — only the direction differs.",
] as const

export const PHASE_4_QUOTES = [
  "Love is the divine law written in the human heart.",
  "To love is to recognize God in disguise.",
  "Love never fails — only fear does. (1 Corinthians 13:8)",
  "Love your enemies, and you destroy the war inside.",
  "The one who forgives twice is free twice.",
  "You are never more divine than when you love the undeserving.",
  "Love is not about reciprocity, but revelation.",
  "To be seen with love is to be resurrected.",
  "There is no growth without compassion.",
  "Love without truth is indulgence; truth without love is violence.",
  "Love teaches you to lose without bitterness and give without counting.",
  "Love is not a feeling — it’s a decision renewed daily.",
  "The cross is the ultimate definition of love: pain offered as healing.",
  "Where love rules, fear cannot dwell.",
  "Love transforms enemies into teachers.",
  "Whoever keeps his heart open under betrayal is undefeatable.",
  "Compassion is the intelligence of the soul.",
  "To be kind when it’s hard is to walk with angels.",
  "The greatest sermon is silent love in action.",
  "Love multiplies when shared and dies when hoarded.",
  "Real love expands your world, not your ego.",
  "Love cannot be forced — it can only be embodied.",
  "Forgiveness is the rebirth of love.",
  "Where there is no judgment, love begins to grow.",
  "Love is not learned; it is remembered.",
] as const

export const PHASE_5_QUOTES = [
  "Life is a brief spark to prepare for eternal dawn.",
  "Each heartbeat is a reminder of divine patience.",
  "Death is not the opposite of life, but its completion.",
  "The wise one counts meaning, not minutes.",
  "The present moment is heaven disguised as routine.",
  "Your time is not your enemy — it is your sculptor.",
  "Every delay has divine design.",
  "To rush is to distrust eternity.",
  "The fear of death disappears when life gains purpose.",
  "Eternity is not after death — it begins in awareness.",
  "You are a traveler through moments, not a prisoner of them.",
  "Every ending conceals a beginning.",
  "What you do with your time becomes your true prayer.",
  "The finite reveals the infinite in disguise.",
  "Waste no hour on what won’t follow you beyond the grave.",
  "God hides eternity in the now.",
  "The clock measures existence; the soul measures experience.",
  "The wise live slowly because they burn brightly.",
  "To die daily is to live divinely.",
  "Mortality is the teacher of humility.",
  "Those who meditate on death live more fully.",
  "Your urgency is sacred when guided by meaning.",
  "Every sunset preaches resurrection.",
  "To remember death is to awaken life.",
  "Time is the test of what deserves eternity.",
] as const

export const PHASE_6_QUOTES = [
  "You cannot serve both God and Mammon. (Matthew 6:24)",
  "Wealth without wisdom becomes chains of gold.",
  "The hand that gives never closes.",
  "What you own should never own you.",
  "Money is not evil — it reveals who rules you.",
  "The rich man is not he who has more, but he who needs less.",
  "Abundance is not possession; it is perception.",
  "Giving transforms currency into current — it makes energy flow.",
  "The poor in spirit are rich in eternity. (Matthew 5:3)",
  "What you give away grows wings.",
  "Your wallet is a mirror of your heart.",
  "True prosperity is usefulness, not luxury.",
  "Wealth is a tool — not an identity.",
  "Gratitude multiplies value without minting new coins.",
  "Greed is hunger with no mouth to feed.",
  "When you give in secret, Heaven takes note. (Matthew 6:4)",
  "Hoarding is fear disguised as strategy.",
  "If your wealth cannot bless others, it will curse you.",
  "The greatest investors are those who plant in souls.",
  "Money flows to purpose, not to pride.",
  "The righteous businessman turns profit into providence.",
  "When generosity becomes instinct, abundance becomes natural.",
  "Spiritual wealth never depreciates.",
  "You can’t buy peace — but peace multiplies everything.",
  "The richest life is one that enriches others.",
] as const

export const PHASE_7_QUOTES = [
  "Your body is the temple of the Holy Spirit. (1 Corinthians 6:19)",
  "The body is prayer made flesh.",
  "To honor the body is to honor the One who breathed life into it.",
  "Presence is worship in motion.",
  "Treat your body as sacred ground — the Spirit walks there.",
  "Breath is the silent gospel of life.",
  "Every movement can become meditation.",
  "Do not abuse the vessel that carries your calling.",
  "Rest is obedience to divine rhythm.",
  "When you eat with gratitude, food becomes communion.",
  "Pain is the whisper of misalignment.",
  "The Spirit teaches through sensation — listen inwardly.",
  "The body’s fatigue often hides the soul’s unrest.",
  "Discipline your body, and your mind will follow.",
  "The body remembers what the soul forgets.",
  "Stillness heals more than striving.",
  "The body reveals truth before the tongue does.",
  "Walk slowly enough to notice God in your breath.",
  "The sacred does not dwell in temples of stone, but in hearts and skin.",
  "To inhabit your body fully is to be resurrected while alive.",
  "Every cell vibrates with divine intention.",
  "Shame pollutes the temple; forgiveness purifies it.",
  "To feel deeply is to touch divinity.",
  "Treat the body as a holy companion, not a servant.",
  "The incarnation of presence is enlightenment.",
] as const

export const PHASE_8_QUOTES = [
  "Faith without works is dead. (James 2:17)",
  "Discipline is divine order made human.",
  "The Spirit’s fire burns brightest in the furnace of consistency.",
  "Every day you master, you multiply your light.",
  "Laziness is silent decay — movement is prayer.",
  "The soul strengthens under structure.",
  "The disciplined man builds eternity one habit at a time.",
  "Freedom without boundaries becomes chaos.",
  "Endurance is the art of holy repetition.",
  "To wake early is to meet God before the world wakes.",
  "Perseverance is faith in motion.",
  "The one who endures temptation becomes unshakable. (James 1:12)",
  "Excellence is worship performed in secret.",
  "Routine is sacred when done with awareness.",
  "The disciplined do not chase motivation — they create momentum.",
  "The flesh resists; the spirit insists.",
  "Comfort is the enemy of calling.",
  "Small acts of order invite great miracles.",
  "Every repetition refines the vessel for revelation.",
  "Spiritual maturity is consistent obedience.",
  "Train your will as you train your muscles — gently, daily, relentlessly.",
  "The path to mastery is paved with quiet sacrifices.",
  "Divine strength grows where discipline meets humility.",
  "When you do what must be done without applause, Heaven applauds.",
  "True mastery is invisible devotion.",
] as const

export const PHASE_9_QUOTES = [
  "The righteous shall live by faith. (Romans 1:17)",
  "Faith is the eye that sees before sight.",
  "He who walks by faith walks above fear.",
  "Doubt is the gatekeeper of miracles.",
  "Trust is not naive — it is prophetic.",
  "When you stop needing proof, proof starts appearing.",
  "Faith begins where certainty ends.",
  "To believe is to participate in creation.",
  "Fear prays to the future; faith listens to eternity.",
  "The soul that trusts cannot drown in chaos.",
  "Every step in darkness builds your inner sun.",
  "The faithful speak from knowing, not hoping.",
  "What you believe shapes what you see.",
  "Faith does not control outcomes; it aligns them.",
  "Hope is faith in rehearsal.",
  "The absence of evidence is not evidence of absence.",
  "To believe without seeing is to see with the soul. (John 20:29)",
  "Faith is divine courage — walking without a map.",
  "What you cannot yet touch is already forming for you.",
  "Every unanswered prayer teaches a deeper trust.",
  "True faith doesn’t demand — it rests.",
  "When faith and patience meet, destiny unfolds.",
  "The faithful man stands still while Heaven rearranges the world.",
  "God hides in the spaces where you let go.",
  "Faith is not waiting — it is walking while it rains.",
] as const

export const PHASE_10_QUOTES = [
  "You are the light of the world. (Matthew 5:14)",
  "True legacy is invisible but undeniable.",
  "What you awaken in others is what will outlive you.",
  "Seeds never see their own forests.",
  "The fruit of your life is the transformation of others.",
  "You write eternity with your daily actions.",
  "Influence is sacred when rooted in service.",
  "Your words are seeds — plant them wisely.",
  "Legacy begins in hidden choices.",
  "What you teach by example becomes eternal.",
  "The greatest inheritance is awareness.",
  "The righteous leave light, not luxury.",
  "You are both someone’s prayer and someone’s answer.",
  "Every generation drinks from wells it did not dig. (John 4:38)",
  "Lead in such a way that your silence still speaks.",
  "The soul’s value is measured by its echoes.",
  "What you give to time will fade; what you give to souls will remain.",
  "Legacy is not remembered — it is felt.",
  "When you live aligned, you become a message.",
  "Every action today is a ripple in eternity.",
  "The Kingdom is built through continuity, not fame.",
  "True inheritance cannot be divided — it multiplies.",
  "The greatest monument is a healed heart.",
  "When others continue your light, Heaven smiles.",
  "You are not the end of your story — you are the beginning of another’s.",
] as const

export const PHASE_QUOTES = {
  1: PHASE_1_QUOTES,
  2: PHASE_2_QUOTES,
  3: PHASE_3_QUOTES,
  4: PHASE_4_QUOTES,
  5: PHASE_5_QUOTES,
  6: PHASE_6_QUOTES,
  7: PHASE_7_QUOTES,
  8: PHASE_8_QUOTES,
  9: PHASE_9_QUOTES,
  10: PHASE_10_QUOTES,
} as const


